inputs:
  version:
    description: "A version to install ecspresso"
    default: "v1.3.2"
runs:
  using: "composite"
  steps:
    - run: |
        if [ ${{ inputs.version }} = "latest" ]; then
          FILENAME=$(curl -sS https://api.github.com/repos/kayac/ecspresso/releases/latest|jq -r '.assets[].name|select(test("linux-amd64.zip"))')
        else
          FILENAME=ecspresso-${{ inputs.version }}-linux-amd64
        fi
        cd /tmp
        curl -sLO https://github.com/kayac/ecspresso/releases/download/${{ inputs.version }}/${FILENAME}.zip
        unzip ${FILENAME}.zip
        sudo install ${FILENAME} /usr/local/bin/ecspresso
        rm -f ${FILENAME} ${FILENAME}.zip
      shell: bash
